demo1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from gesconweb import views
import debug_toolbar

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^gesconweb/', include('gesconweb.urls', namespace='apps')),
    url(r'^hola/(\d{4})-?([a-zA-Z]{3})/$', views.hola),
    # url(r'^hola/([a-z]+)/$', views.hola),
    ]

gesconweb/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^app/(\d+)/$', views.detalle_aplicativo, name='detalle_aplicativo'),
    ]

comun/models.py
from django.db import models

# Create your models here.

gesconweb/models.py
from django.db import models
from django.contrib.auth.models import Group

# Create your models here.

class Aplicativo(models.Model):

    nombre = models.CharField(max_length=82)
    url = models.URLField(max_length=400)
    f_creacion = models.DateField(auto_now_add=True)
    email = models.EmailField(max_length=300, blank=True)
    telefono = models.CharField(max_length=12, blank=True)
    descripcion = models.TextField()
    activo = models.BooleanField(default=True)
    slug = models.SlugField(max_length=32)

    def __str__(self):
        return '{} (Creada el {})'.format(self.nombre, self.f_creacion)

class Permiso(models.Model):
    aplicativo = models.ForeignKey(Aplicativo)
    grupo = models.ForeignKey(Group)
    f_creacion = models.DateField(auto_now_add=True)
    orden = models.IntegerField(default=0)

    def __str__(self):
        return 'Permiso al grupo {} para el aplicativo {}'.format(
            self.grupo,
            self.aplicativo,
            )

comun/views.py
from django.shortcuts import render

# Create your views here.

gesconweb/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*- 

from django.shortcuts import render
from django.http import HttpResponse

import datetime
import os

from django.contrib.auth.models import Group
from .models import Aplicativo, Permiso

# Create your views here.


def homepage(request):
    apps = list(
        Aplicativo.objects
        .prefetch_related('permiso_set')
        .all()
        )
    return render(request, 'gesconweb/homepage.html', {
        'apps': apps,
        }) 


def detalle_aplicativo(request, id_app):
    id_app = int(id_app)
    app = Aplicativo.objects.get(pk=id_app)
    grupos = [p.grupo for p in Permiso.objects
        .select_related('grupo')
        .filter(aplicativo=app)
        .order_by('orden')
        ]
    
    return render(request, 'gesconweb/detalle_aplicativo.html', {
        'aplicativo': app,
        'grupos': grupos,
        })

def lista_grupos(request):
    grupos = Group.objects.all().order_by('name')
    grupos = grupos.select_related('permiso_set')
    return render(request, 'gesconweb/lista_grupos.html', {
        'grupos': grupos, 
        })

def hola(request, numeros, letras):
    return HttpResponse('Matrícula (<i>normalizada</i>): <b><tt>{}{}</tt></b>'.format(
        numeros,
        letras.upper(),
        )
        )

gesconweb/templates/gesconweb/detalle_aplicativo.html
{% extends 'base.html' %}

{% block title %} Listado de grupos {% endblock %}

{% block content %}

<h1> {{ aplicativo.nombre }} </h1>

<dl>
    <dt>url</dt>
    <dd>{{ aplicativo.url }}</dd>
    <dt>activo</dt>
    <dd>{{ aplicativo.activo }}</dd>
</dl>

<h2> Grupos con permiso para usar este aplicativo</h2>

<ul>
{% for grupo in grupos %}
<li> {{ grupo }} </li>
{% endfor %}
</ul>

{% endblock %}

gesconweb/templates/gesconweb/homepage.html
{% extends 'base.html' %}

{% block title %}Listado de aplicaciones{% endblock %}

{% block content %}

<h1>Aplicaciones <small>Todas</small></h1>
<h2>Hay <span class="badge">{{ apps|length }}</span> aplicaciones.</h2>

<table class="table table-striped">
 <thead>
  <tr>
    <th>Nombre</th>
    <th>Descripción
    <th>Activo</th>
    <th>Permisos</th>
  </tr>
 </thead>
 <tbody>
    {% for app in apps %}
      <tr>
          <td> <a href="{% url 'apps:detalle_aplicativo' app.id %}"> {{ app.nombre }} <a></td>
          <td> {{ app.descripcion }} </td>
          <td> {{ app.activo }} </td>
          <td> permiso:  {{ app.permiso_set.all }} </td>
      </tr>
    {% endfor %}
 </tbody>
</table>


{% endblock %}

{% block icono %} {% endblock %}

gesconweb/templates/gesconweb/lista_grupos.html
{% extends 'base.html' %}

{% block title %} Listado de grupos {% endblock %}

{% block content %}

<h1>Listado de grupos</small></h1>
<h2>Hay <span class="badge">{{ grupos|length }}</span> grupos.</h2>

<table class="table table-striped">
 <thead>
  <tr>
    <th>Nombre</th>
    <th>Permisos</th>
  </tr>
 </thead>
 <tbody>
    {% for g in grupos %}
      <tr>
          <td> {{ g.name }} </td>
          <td> <ul>{% for p in g.permiso_set.all %}
                 <li> {{ p }}</li>
                 {% endfor %}
            </ul>
          </td>
      </tr>
    {% endfor %}
 </tbody>
</table>


{% endblock %}

{% block icono %} {% endblock %}

gesconweb/templates/gesconweb/lista_permisos.html
{% extends 'base.html' %}

{% block title %} Listado de grupos {% endblock %}

{% block content %}

<h1>Listado de grupos</small></h1>
<h2>Hay <span class="badge">{{ grupos|length }}</span> grupos.</h2>

<table class="table table-striped">
 <thead>
  <tr>
    <th>Nombre</th>
    <th>Permisos</th>
  </tr>
 </thead>
 <tbody>
    {% for g in grupos %}
      <tr>
          <td> {{ g.name }} </td>
          <td> <ul>{% for p in g.permiso_set.all %}
                 <li> {{ p }}</li>
                 {% endfor %}
            </ul>
          </td>
      </tr>
    {% endfor %}
 </tbody>
</table>


{% endblock %}

{% block icono %} {% endblock %}